[server]
# Optimize for Streamlit Cloud
maxUploadSize = 200
maxMessageSize = 200
enableCORS = true
enableXsrfProtection = true

# Performance optimization
enableStaticServing = false
runOnSave = true
fileWatcherType = "auto"

[browser]
gatherUsageStats = false

[client]
# Reduce connection timeouts for faster experience
showErrorDetails = true
toolbarMode = "minimal"


[runner]
# Optimize script execution
magicEnabled = true
fastReruns = true
postScriptGC = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname)s %(message)s"
